#!/bin/bash

url=$1
# 09-07-2017 19:52
start_dt=$2
end_dt=$3

current_epoch=$(date +%s)
start_epoch=$(date  -j -f "%d-%m-%Y %H:%M:%S" "$start_dt:00" +%s)
start_sleep_seconds=$(( $start_epoch - $current_epoch ))

end_epoch=$(date  -j -f "%d-%m-%Y %H:%M:%S" "$end_dt:00" +%s)
end_sleep_seconds=$(( $end_epoch - $start_epoch ))

echo "Sleeping until $start_dt ($start_sleep_seconds secs)"
sleep $start_sleep_seconds

#log_file="youtube-dl-${start_epoch}.log"
echo "Starting download"

echo "Scheduling stop at $end_dt ($end_sleep_seconds secs)"
(sleep $end_sleep_seconds ; kill -INT `ps | grep "$url" | grep -v grep | awk '{ print $1 }'`) &

youtube-dl "$url"

#YT_PID=$!
#echo "PID = $YT_PID"
#sleep $end_sleep_seconds
#kill -INT $YT_PID